"""
plot_brier_analysis.py
========================

This script reads Brier score data produced from the calibration benchmark
(see ``brier_scores_results.csv``) and produces a two‑panel figure summarising
the distribution of Brier scores across calibration methods.  The left panel
shows a boxplot of **ID Brier scores** for each method across backbones with
jittered dots for individual backbone values and a label indicating how many
backbones each method wins (``N_best``).  The right panel summarises
**ΔBrier = Brier_OOD − Brier_ID** across backbones using a forest plot:
medians as points, interquartile ranges as thick bars, 10–90th percentile
whiskers, and the fraction of backbones with improvement (negative ΔBrier).

Usage
-----

Place ``brier_scores_results.csv`` (generated by the companion script
``compute_brier_scores.py``) in the same directory.  Then run:

    python plot_brier_analysis.py

The script will save a PNG file called ``brier_analysis_figure.png`` in
the current directory and write summary statistics to ``brier_summary.csv``.

Dependencies:  pandas, numpy, matplotlib.  Install with
``pip install pandas numpy matplotlib`` if needed.
"""

import math
import pathlib
from typing import Dict, List

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def load_brier_data(csv_path: pathlib.Path) -> pd.DataFrame:
    """Load the Brier results CSV into a DataFrame.

    The CSV must contain columns: backbone, method, acc_id, acc_ood,
    ece_id, ece_ood, brier_id, brier_ood, brier_delta.
    """
    df = pd.read_csv(csv_path)
    expected_cols = {
        "backbone",
        "method",
        "brier_id",
        "brier_ood",
        "brier_delta",
    }
    if not expected_cols.issubset(df.columns):
        missing = expected_cols - set(df.columns)
        raise ValueError(
            f"CSV file missing required columns: {', '.join(sorted(missing))}"
        )
    return df


def prepare_id_distribution(df: pd.DataFrame) -> (Dict[str, List[float]], Dict[str, float]):
    """Prepare Brier distributions and N_best counts for ID data.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame with columns ``backbone``, ``method``, and ``brier_id``.

    Returns
    -------
    brier_by_method : Dict[str, List[float]]
        Mapping from method to list of ID Brier scores across backbones.
    best_counts : Dict[str, float]
        Mapping from method to count of backbones where it achieves the
        minimum ID Brier (ties split evenly).
    """
    brier_by_method: Dict[str, List[float]] = {}
    best_counts: Dict[str, float] = {}
    for method in df["method"].unique():
        brier_by_method[method] = []
        best_counts[method] = 0.0

    # Compute distribution per method
    for _, row in df.iterrows():
        brier_by_method[row["method"]].append(row["brier_id"])

    # Compute N_best counts
    grouped = df.groupby("backbone")
    for _, group in grouped:
        # drop rows with NaN brier_id
        valid_rows = group.dropna(subset=["brier_id"])
        if valid_rows.empty:
            continue
        min_val = valid_rows["brier_id"].min()
        is_best = valid_rows["brier_id"].values == min_val
        k = is_best.sum()
        if k > 0:
            share = 1.0 / k
            for method, flag in zip(valid_rows["method"], is_best):
                if flag:
                    best_counts[method] += share

    return brier_by_method, best_counts


def prepare_delta_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Compute summary statistics for ΔBrier across backbones per method.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame with columns ``method`` and ``brier_delta``.

    Returns
    -------
    summary_df : pd.DataFrame
        DataFrame with summary statistics per method: median, q25, q75,
        q10, q90, N (count), and improve_rate (fraction of negative deltas).
    """
    summary_list = []
    grouped = df.groupby("method")
    for method, g in grouped:
        vals = g["brier_delta"].dropna().values
        if len(vals) == 0:
            continue
        median = float(np.nanmedian(vals))
        q25 = float(np.nanpercentile(vals, 25))
        q75 = float(np.nanpercentile(vals, 75))
        q10 = float(np.nanpercentile(vals, 10))
        q90 = float(np.nanpercentile(vals, 90))
        improve_rate = float((vals < 0).sum() / len(vals))
        summary_list.append(
            {
                "method": method,
                "median": median,
                "q25": q25,
                "q75": q75,
                "q10": q10,
                "q90": q90,
                "N": len(vals),
                "improve_rate": improve_rate,
            }
        )

    summary_df = pd.DataFrame(summary_list)
    # sort by median delta ascending (more negative is better)
    summary_df = summary_df.sort_values("median", ascending=True).reset_index(drop=True)
    return summary_df


def plot_brier_analysis(
    brier_by_method: Dict[str, List[float]],
    best_counts: Dict[str, float],
    summary_df: pd.DataFrame,
    output_path: pathlib.Path,
) -> None:
    """Generate a two‑panel figure summarising Brier scores.

    Left panel: boxplot of ID Brier scores per method with jittered backbone points
               and labels showing how many backbones each method wins.
    Right panel: forest plot summarising ΔBrier across backbones per method.

    Parameters
    ----------
    brier_by_method : dict
        Mapping from method to list of ID Brier scores.
    best_counts : dict
        Mapping from method to count of backbones where it is best (ID).
    summary_df : pd.DataFrame
        Summary statistics for ΔBrier (output of prepare_delta_summary).
    output_path : pathlib.Path
        Location to save the PNG figure.
    """
    methods = list(brier_by_method.keys())
    # Sort by median ID brier (lower is better)
    methods_sorted = sorted(
        methods,
        key=lambda m: np.nanmedian(brier_by_method[m]) if len(brier_by_method[m]) > 0 else math.inf,
    )

    # Build boxplot data
    box_data = [np.array(brier_by_method[m]) for m in methods_sorted]

    # Colour palette for jittered points (cycle through matplotlib default)
    colors = plt.rcParams["axes.prop_cycle"].by_key()["color"]

    fig, axs = plt.subplots(1, 2, figsize=(13, 6), gridspec_kw={'width_ratios': [3, 2]})
    # Left panel: boxplots
    ax = axs[0]
    flierprops = dict(
        marker="o",
        markerfacecolor="none",
        markeredgecolor="k",
        markersize=5,
        alpha=0.8,
    )
    meanprops = dict(
        marker="^",
        markerfacecolor="tab:green",
        markeredgecolor="tab:green",
        markersize=7,
    )
    ax.boxplot(
        box_data,
        labels=methods_sorted,
        whis=[10, 90],
        showmeans=True,
        flierprops=flierprops,
        meanprops=meanprops,
    )
    # Jittered points
    rng = np.random.default_rng(12345)
    for i, m in enumerate(methods_sorted, start=1):
        vals = np.array(brier_by_method[m])
        x_jitter = rng.random(len(vals)) * 0.2 - 0.1
        ax.scatter(np.full_like(vals, i) + x_jitter, vals, s=20, color=colors[(i - 1) % len(colors)], alpha=0.85)

    ax.set_ylabel("Brier Score (ID)")
    ax.set_title("ID Brier Scores Across Backbones")
    # Add N_best labels above boxes
    ymin, ymax = ax.get_ylim()
    ax.set_ylim(ymin, ymax * 1.05)
    for i, m in enumerate(methods_sorted, start=1):
        n_best = best_counts.get(m, 0.0)
        text = f"N_best={n_best:.0f}" if abs(n_best - round(n_best)) < 1e-6 else f"N_best={n_best:.1f}"
        ax.text(i, 0.97, text, transform=ax.get_xaxis_transform(), ha="center", va="top", fontsize=9)
    # Beautify
    for side in ["top", "right", "bottom", "left"]:
        ax.spines[side].set_visible(True)
        ax.spines[side].set_linewidth(1.2)
    ax.tick_params(axis="x", rotation=25)

    # Right panel: forest plot for ΔBrier
    ax2 = axs[1]
    y_pos = np.arange(len(summary_df))[::-1]
    # horizontal line at 0
    ax2.axvline(0.0, linestyle="--", linewidth=1, color="gray")
    # Whiskers (10–90)
    for y, q10, q90 in zip(y_pos, summary_df["q10"], summary_df["q90"]):
        ax2.hlines(y, q10, q90, linewidth=1, color="gray")
    # IQR bars (25–75)
    for y, q25, q75 in zip(y_pos, summary_df["q25"], summary_df["q75"]):
        ax2.hlines(y, q25, q75, linewidth=6, color="tab:blue")
    # Median points
    ax2.scatter(summary_df["median"], y_pos, marker="o", color="tab:red", s=40)
    ax2.set_yticks(y_pos)
    ax2.set_yticklabels(summary_df["method"])
    ax2.set_xlabel("ΔBrier (OOD − ID)")
    ax2.set_title("ΔBrier Summary (OOD vs. ID)")
    # Right panel annotations: N_backbones | improve_rate
    x_min, x_max = ax2.get_xlim()
    for y, n, ir in zip(y_pos, summary_df["N"], summary_df["improve_rate"]):
        ax2.text(x_max, y, f"N={n} | improve={int(ir * 100)}%", va="center", ha="right", fontsize=8)
    # Beautify
    for side in ["top", "right", "bottom", "left"]:
        ax2.spines[side].set_visible(True)
        ax2.spines[side].set_linewidth(1.2)
    ax2.tick_params(axis="y", which="both", length=0)

    fig.suptitle("Calibration Methods: Brier Score Analysis", fontsize=14, y=1.02)
    fig.tight_layout()
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    print(f"Figure saved to {output_path}")


def main():
    """Main entry point."""
    # Locate CSV file
    csv_path = pathlib.Path("brier_scores_results.csv")
    if not csv_path.exists():
        raise FileNotFoundError(f"{csv_path} not found. Run compute_brier_scores.py first.")
    df = load_brier_data(csv_path)
    # Prepare ID distribution and N_best
    brier_by_method, best_counts = prepare_id_distribution(df)
    # Prepare delta summary
    summary_df = prepare_delta_summary(df)
    # Save summary to CSV
    summary_df.to_csv("brier_delta_summary.csv", index=False)
    print("Summary saved to brier_delta_summary.csv")
    # Plot and save figure
    output_path = pathlib.Path("brier_analysis_figure.png")
    plot_brier_analysis(brier_by_method, best_counts, summary_df, output_path)


if __name__ == "__main__":
    main()